CREATE DATABASE QLHS
USE QLHS
CREATE TABLE DIEM(
MAHS char(5) NOT NULL,
DK1 numeric(2,1),
DK2 numeric(2,1),
DK3 numeric(2,1),
DTB numeric(2,1),
XL nvarchar(5),
CONSTRAINT PK_DIEM PRIMARY KEY (MAHS),
--RANG BUOC DIEM TU 0->10
CHECK (DK1 BETWEEN 0 AND 10),
CHECK (DK2 BETWEEN 0 AND 10),
CHECK (DK3 BETWEEN 0 AND 10))
--DROP TABLE DIEM

CREATE TABLE HOCSINH(
MAHS char(5) NOT NULL,
HO nvarchar(20),
TEN nvarchar(10),
DC nvarchar(30),
MALOP nvarchar(5),
NGAYSINH datetime,
CONSTRAINT PK_HOCSINH PRIMARY KEY (MAHS))
--DROP TABLE HOCSINH

--TAO THAM CHIEU TOAN VEN
ALTER TABLE DIEM 
ADD FOREIGN KEY (MAHS) REFERENCES HOCSINH(MAHS)

--NHAP DU LIEU
INSERT INTO DIEM VALUES('HS01',7.6,8.3,9.2,NULL,NULL)
INSERT INTO DIEM VALUES('HS02',7.0,9.0,6.8,NULL,NULL)
INSERT INTO DIEM VALUES('HS03',8.0,8.3,9.0,NULL,NULL)
INSERT INTO DIEM VALUES('HS04',6.5,6.0,7.0,NULL,NULL)
INSERT INTO DIEM VALUES('HS05',5.0,5.0,5.0,NULL,NULL)
INSERT INTO DIEM VALUES('HS06',0,0,0,NULL,NULL)
INSERT INTO DIEM VALUES('HS07',0,0,0,NULL,NULL)
/* NOTE: insert dữ liệu bảng học sinh trước khi insert dữ liệu bảng điểm,
	vì ở trên mình đã tạo tham chiếu MHS (bảng DIEM) tới MHS (bảng HOCSINH),
	nên có dữ liệu trong bảng HOCSINH (cụ thể là MAHS)
	mới tham chiếu được MHS bảng DIEM tới MHS bảng HOCSINH
	//Mò mãi mới ra :v
*/
INSERT INTO HOCSINH VALUES('HS01','NGUYEN VAN','TOAN','HANOI','L01',1999-04-02)
INSERT INTO HOCSINH VALUES('HS02','CAO VAN','TINH','HAIPHONG','L01',1999-03-02)
INSERT INTO HOCSINH VALUES('HS03','HO QUANG','HIEU','BUONMATHUOT','L02',1999-12-09)
INSERT INTO HOCSINH VALUES('HS04','NGUYEN CONG','PHUONG','HANOI','L02',1999-06-12)
INSERT INTO HOCSINH VALUES('HS05','PHAN VAN','QUYET','HANOI','L03',1999-07-08)
INSERT INTO HOCSINH VALUES('HS06','CAO VAN','NHAN','HANOI','L03',1999-09-10)
INSERT INTO HOCSINH VALUES('HS07','LE THANH','CONG','HANOI','L03',1999-07-08)

--XEM DANH SACH HOC SINH THIEU DIEM CA 3 HOC KY
/* Viết đúng mà chạy ứ được :v . Nên đổi điểm từ NULL sang 0
SELECT HOCSINH.HO+' '+HOCSINH.TEN FROM HOCSINH 
INNER JOIN DIEM ON DIEM.MAHS = HOCSINH.MAHS
WHERE (DIEM.DK1=NULL AND DIEM.DK2=NULL AND DIEM.DK3=NULL)
*/
SELECT HOCSINH.HO+' '+HOCSINH.TEN FROM HOCSINH 
INNER JOIN DIEM ON DIEM.MAHS = HOCSINH.MAHS
WHERE (DIEM.DK1=0 AND DIEM.DK2=0 AND DIEM.DK3=0)
--CAP NHAT COT DTB, XL
UPDATE DIEM SET DTB=(DK1+DK2+DK3)/3
UPDATE DIEM SET XL=CASE
			WHEN DTB>=8 THEN N'Giỏi'
			WHEN DTB>=6.5 THEN N'Khá'
			WHEN DTB>5 THEN N'Trung bình'
			ELSE N'Yếu'
			END

--TAO BANG HOCBONG
CREATE FUNCTION HOCBONG()
RETURNS TABLE
AS RETURN (SELECT HOCSINH.HO+' '+HOCSINH.TEN AS HOVATEN,DTB FROM HOCSINH
			INNER JOIN DIEM ON DIEM.MAHS = HOCSINH.MAHS
			WHERE (DIEM.DTB>=7 AND DIEM.DK1!=0 AND DIEM.DK2!=0 AND DIEM.DK3!=0))
SELECT * FROM HOCBONG() --XEM BẢNG

--XEM DANH SACH SINH VIEN CO DIEM TRUNG BINH CAO NHAT
SELECT TOP 1 HOCSINH.HO+' '+HOCSINH.TEN AS HOVATEN,DTB FROM HOCSINH
			INNER JOIN DIEM ON DIEM.MAHS = HOCSINH.MAHS

--CHO BIET CO BAO NHIEU HOC SINH GIOI
SELECT COUNT (*) FROM DIEM WHERE XL=N'Giỏi'
